# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: /home/20195435/projects/data/LINEMOD_updated/occlusion/train.txt 
val: /home/20195435/projects/data/LINEMOD_updated/occlusion/test.txt 

mesh0: /home/20195435/projects/data/LINEMOD_updated/ape/ape.ply
mesh1: /home/20195435/projects/data/LINEMOD_updated/can/can.ply
mesh2: /home/20195435/projects/data/LINEMOD_updated/cat/cat.ply
mesh3: /home/20195435/projects/data/LINEMOD_updated/driller/driller.ply
mesh4: /home/20195435/projects/data/LINEMOD_updated/duck/duck.ply
mesh5: /home/20195435/projects/data/LINEMOD_updated/eggbox/eggbox.ply
mesh6: /home/20195435/projects/data/LINEMOD_updated/glue/glue.ply
mesh7: /home/20195435/projects/data/LINEMOD_updated/holepuncher/holepuncher.ply

names : ["ape", "can", "cat", "driller", "duck", "eggbox", "glue", "holepuncher"]

background_path: "../data/VOCdevkit/VOC2012/JPEGImages"
coords: 18

diam0: 0.103
diam1: 0.202
diam2: 0.155
diam3: 0.262
diam4: 0.109
diam5: 0.176364
diam6: 0.176
diam7: 0.162

gpus : 0

width : 640
height : 480

nc: 8  # number of classes

fx: 572.4114 
fy: 573.5704
u0: 325.2611
v0: 242.0489